module.exports = [
  {
    id: 1,
    name: "HTML",
    level: "100%",
    icon: "img/skills/html.webp",
    pinned: false,
  },
  {
    id: 2,
    name: "CSS",
    level: "95%",
    icon: "img/skills/css.webp",
    pinned: true,
  },
  {
    id: 3,
    name: "javascript",
    level: "80%",
    icon: "img/skills/js.webp",
    pinned: true,
  },
  {
    id: 4,
    name: "SASS",
    level: "80%",
    icon: "img/skills/sass.webp",
    pinned: false,
  },
  {
    id: 5,
    name: "bootstrap",
    level: "90%",
    icon: "img/skills/bootstrap.webp",
    pinned: false,
  },
  {
    id: 6,
    name: "react",
    level: "80%",
    icon: "img/skills/reactjs.webp",
    pinned: true,
  },
  {
    id: 7,
    name: "tailwind",
    level: "70%",
    icon: "img/skills/tailwind.webp",
    pinned: true,
  },
  {
    id: 8,
    name: "C Programming",
    level: "80%",
    icon: "img/skills/c.webp",
    pinned: false,
  },
  {
    id: 9,
    name: "C++",
    level: "60%",
    icon: "img/skills/cpp.webp",
    pinned: false,
  },
  {
    id: 10,
    name: "Python",
    level: "90%",
    icon: "img/skills/python.webp",
    pinned: true,
  },
  {
    id: 11,
    name: "MySQL",
    level: "85%",
    icon: "img/skills/mysql.webp",
    pinned: false,
  },
  {
    id: 12,
    name: "git",
    level: "95%",
    icon: "img/skills/git.webp",
    pinned: false,
  },
  {
    id: 13,
    name: "Django",
    level: "30%",
    icon: "img/skills/django.webp",
    pinned: false,
  },
  {
    id: 14,
    name: "Nodejs",
    level: "50%",
    icon: "img/skills/nodejs.webp",
    pinned: false,
  },
  {
    id: 15,
    name: "Firebase",
    level: "50%",
    icon: "img/skills/firebase.webp",
    pinned: false,
  },
  {
    id: 16,
    name: "Data Structure",
    level: "60%",
    icon: "img/skills/ds.webp",
    pinned: false,
  },
  {
    id: 17,
    name: "Photoshop",
    level: "75%",
    icon: "img/skills/photoshop.webp",
    pinned: false,
  },
  {
    id: 18,
    name: "MS Office",
    level: "65%",
    icon: "img/skills/msOffice.webp",
    pinned: false,
  },
  {
    id: 19,
    name: "Figma",
    level: "75%",
    icon: "img/skills/figma.webp",
    pinned: false,
  },
];
