import Head from "next/head";
import CoverPage from "../components/CoverPage";
import ScrollToTopButton from "../components/ScrollToTopButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverPage
        title="Hi There! I am"
        className="flex flex-col justify-center items-center"
        mainHeading="Jatin Sharma"
        childrenClass="text-[40px] ml-0"
      >
        <p className="font-light text-xl text-white">{"<React Developer />"}</p>
      </CoverPage>
      {/* <div className="pt-24">Home</div> */}
      <ScrollToTopButton />
    </>
  );
}
